#!/bin/bash
sudo pacman -S openssh
sudo systemctl enable sshd
mkdir /home/groa/.ssh
curl https://raw.githubusercontent.com/msl6030/arch/main/authorized_keys -o /home/groa/.ssh/authorized_keys
sed -i "/#UsePAM no/c\UsePAM no" /etc/ssh/sshd_config
sed -i "/#PermitRootLogin prohibit-password/c\PermitRootLogin no" /etc/ssh/sshd_config
sed -i "/#PasswordAuthentication yes/c\PasswordAuthentication no" /etc/ssh/sshd_config
systemctl reload sshd
